### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [leswright1977/PySpectrometer#1]
Hello!

I found link to this project from https://hackaday.com/2021/04/23/pi-based-spectrometer-puts-the-complexity-in-the-software/

Could you please add information about license of this repository — is it allowed to copy, change and use the code and images in any purpose?
It would be great to see any popular open source license.

**Comment by leswright1977** [comment]
Done! Enjoy!

**Comment by vazhnov** [comment]
Apache v2.0 — great!
@leswright1977, thank you!
