### ISSUE TITLE
Project can't be cloned on Windows

### ISSUE THREAD

**Issue by astuder** [leswright1977/PySpectrometer#17]
This project currently can't be cloned onto a Windows machine due to the colons in the filename of this image:
`media/spectrum-09-04-2021-15:19:27.jpg`

Renaming the file to something like spectrum-09-04-2021-15-19-27.jpg will solve this issue.

**Comment by resnikal71202** [comment]
a temporary fix would be to run ```git restore --source=HEAD :/``` but yes renaming would be great

**Comment by leswright1977** [comment]
It will be fixed in the next release.
