### ISSUE TITLE
How to remove LES WRIGHT 2021 from the Project?

### ISSUE THREAD

**Issue by B4xAbhishek** [leswright1977/PySpectrometer#25]

**Comment by StripeyType** [comment]
You may not.

This project is Apache 2.0 Licensed, and Copyright notifications must be retained under the terms of this license.

(see: [LICENSE](https://github.com/leswright1977/PySpectrometer/blob/main/LICENSE))

**Comment by leswright1977** [comment]
As above. The software is free and useful, why expunge the author, except to plagiarize?
