### ISSUE TITLE
Averaging to remove sensor noise

### ISSUE THREAD

**Issue by antonzuykov** [leswright1977/PySpectrometer#28]
I suggest adding some sort of averaging from several frames, so that sensor noise doesn't get captured as legitimate spectrum data. Ideally, user should be able to toggle this function on/off as necessary. 

I have not looked at the code too much yet, only at a glance. Besides python is not my number one language, but I am willing to help you add something that does the averaging. 

Also, if you accept it, I saw some room for improvement with the code. 

Me: US based software engineer by trade. 

ps: averaging can be done by grabbing data from several rows above and below the "main scan line", instead of waiting for several frames to accumulate.

**Comment by leswright1977** [comment]
I am in the process of creating a new version of this, and may well incorporate it.
Currently the software has a savgol filter to dispose of noise, however there may be an advantage to pulling several imes from the camera,

**Comment by leswright1977** [comment]
Done  in the new version of: https://github.com/leswright1977/PySpectrometer2
