### ISSUE TITLE
2021-01-11-raspios-buster-armhf too old for Rpi 4

### ISSUE THREAD

**Issue by 68artik** [leswright1977/PySpectrometer#29]
I just bought the Rpi 4 for wonderful pyspectrometer project. 

Unfortunately my Rpi4 cannot boot itself with recommended 2021-01-11-raspios-buster-armhf.
The Legacy and 2021-03-04-raspios-buster does not allow to install scipy. 
The computer gets unrensponsive so I have to make a hard reset.

Any help would be very appreciated!

Regards
Andrzej

![Screenshot 3](https://user-images.githubusercontent.com/114232300/191965167-b884efaa-4277-4463-a09f-3549d5cef7ad.jpg)

**Comment by leswright1977** [comment]
Thanks for the heads up!
It seems Bullseye has broken everything, the camera, peakutils and scipy!
I am working on a new version now with the new picamera2 library.
Check back often, I am expecting to have something in alpha shortly!

**Comment by 68artik** [comment]
Thank so much Les! I'll follow this thread patiently! Your project is **super awesome**

**Comment by 68artik** [comment]
FYI: My friend has older Raspberry Pi 4 I guess with an earlier firmware. He can boot Pi using Buster but unfortunately he can not install python open cv (sudo apt-get install python3-opencv is broken with an errors).

**Comment by leswright1977** [comment]
A new Raspberry Pi OS Bullseye compatible version of this software is now available in src/PySpectrometer-3.2! This is a quick ugly hack to simply get this thing working on Bullseye and keep everyone happy, whilst I get time to work on the latest and greatest version of this software.

For now, simply download the contents of 3.2, read the new README file, install the dependencies (only two now), do a little raspi-config, and have fun!

**Comment by leswright1977** [comment]
Additionally, it throws a Gstreamer warning in the console on start, but it does not seem to affect anything!
let me know if there are any serious issues with 3.2

**Comment by 68artik** [comment]
Wonderful! It works! Will test it more soon. Thank you for your fast response...

**Comment by leswright1977** [comment]
Outstanding! :-)

**Comment by leswright1977** [comment]
See new version: https://github.com/leswright1977/PySpectrometer2
