### ISSUE TITLE
Feature request: long time exposure

### ISSUE THREAD

**Issue by gon0** [leswright1977/PySpectrometer#3]
Dear Les,

this is a great project. Thank you for sharing! I found it via hackaday. 

I am thinking about if I could use it for astronomy. Because the light sources (stars) are very dim, a long time exposure would be needed. Is there an advantage if the HQ Pi Cam is used instead of the Standard Pi cam for this case?

I just leave my thought for a long time exposure here for discussion. I more people are interested, maybe someone could implement it. Otherwise just close this ticket.

Keep up the great work :)

**Comment by leswright1977** [comment]
Cheers!
Yes, probably. The picam 2 has a max exposure time of 10 seconds, and the HQ can do up to 230 seconds: https://www.raspberrypi.org/documentation/usage/camera/raspicam/longexp.md

I suppose on the picam2, you could stack images, then run the algorithm against it.
If I get time, and manage to get an HQ cam, it is definitely worth looking into.

Cheers!

Les

**Comment by MakerMatrix** [comment]
I have the HQ camera and plan to try that, first.  I can experiment with the exposure times.

Another option I'm interested in exploring is using the diffraction films with 1000 slits/mm.

Great software.  I have wanted to make one of these for a long time.  I was planning to use the older closed-source Windows software that does more or less the same thing.  Thank you for building the software for Pi/Linux and making it open.  I think you can easily make a functional, portable solution with this.  Really great.

**Comment by leswright1977** [comment]
Awesome. Let me know how you get on with the HQ cam.
There is quite a bit of interest in this stuff.

You are welcome, I hope you get some good use out of it!

**Comment by gon0** [comment]
Dear @leswright1977 and @MakerMatrix,
thank you for your quick help! Since I don't have any PiCam, I am curious waiting for your results to decide what to buy :) (Especially the HQ cam with a 1000 slits/mm grating sounds interesting)

Also I thought about the movement of the spectrum in the camera picture, if the light source moves. E.g. if a star moves and I point to it with a telescope without tracking, will the spectrum in the camera also move?  I am willing to try that out. Some thought about that:
- if the spectum moves, a long time exposure would probably broaden the measured peaks
- if the spectrum does not move, this is good, but:
Since I have a cheap telescope, I might measure also chromatic aberrations of my telescope when the star moves from one corner to another. But this is a side effect. I am just curious measuring different spectra ;)

Thank you for your great work so far!

**Comment by MakerMatrix** [comment]
I'm all in on the astro bits.  I have an EQ6 and AVX tracking mounts here.  We could maybe fabricate something that interfaces with a standard 2" focuser.  The challenge for me is always time, not motivation ;-)

The gratings I have are in 35mm slide form, like this:
https://www.ebay.com/itm/292860945062

Also I just found (and ordered) this for making custom sizes/shapes:
https://www.ebay.com/itm/280859388704

They are probably cheap and abundant on ebay in every part of the world.  I've noticed they tend to come from Israel.

**Comment by GoJian** [comment]
Just ordered all parts and I have to say I am really excited about this project!

@MakerMatrix - thanks for all the ideas. I just ordered some 1000 line/mm gratings as well. From studying this [ebay seller's listing](https://www.ebay.com/itm/320403244106), I learned two things (1) the diffraction grating was mounted ~45 degrees to incident light -- not sure why? (2) there is another, prism-type spectroscope that seems better. There also appears to be some inherent non-linearity in how the diffraction works.

I am looking for a suitable c-mount zoom lens for the HQ Pi Cam. I guess I will need to test out a few C-mount CCTV lenses. Will report back once I get all the parts together.

In addition to attaching this to a telescope (please let us know once anyone figure out a suitable adapter), I hope to attach this setup to a microscope camera port, so I can use this to measure the spectra of small objects and minerals.

**Comment by MakerMatrix** [comment]
My little scope came today.  It seems pretty awesome.
![IMG_3959](https://user-images.githubusercontent.com/52144433/116790810-f13df180-aa7b-11eb-8d59-6653d07bdc89.JPEG)
![IMG_3958](https://user-images.githubusercontent.com/52144433/116790811-f1d68800-aa7b-11eb-865a-a11f01444cbf.JPEG)
