### ISSUE TITLE
dependency PIL.ImageTk missing

### ISSUE THREAD

**Issue by sigmaeo** [leswright1977/PySpectrometer#8]
I start with fresh image "Raspberry Pi Os with Desktop" (from 2021-03-04) and got:
```
pi@raspberrypi:~/PySpectrometer/src $ python3 pyspectrometer-v3.py
Traceback (most recent call last):
  File "pyspectrometer-v3.py", line 46, in <module>
    import PIL.Image, PIL.ImageTk
ModuleNotFoundError: No module named 'PIL.ImageTk'
```

It seems, that one dependency is missing - I had to add:
**sudo apt-get install python3-pil.imagetk**

**Comment by leswright1977** [comment]
Weird! I will add it to the dependencies file, thanks!
